device: "cpu"
image:
  portrait_effect:
    depth_threshold: 0.65
    blur_kernel: 32
  super_resolution:
    target_size: 128
    scale_factor: 1.5
    upscale_factor: 4
  background_removal:
    confidence_threshold: 0.5
    use_fp16: false  # Disabled for MPS compatibility
audio:
  transcription:
    model: "base"
    chunk_duration: 10.0
    overlap_duration: 0.5
    language: "auto"
    task: "transcribe"
  denoise:
    noise_clip_sec: 0.5  # seconds of audio to use as noise profile
    prop_decrease: 1.0   # amount of noise reduction (0-1)
    stationary: true     # stationary noise reduction
    n_std_thresh_stationary: 1.5  # threshold for stationary noise
