name: nuggetapp
on: 
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run bundle:prod:src
      - run: electron-builder build --win --x64 -p always

